version: '3.8'

services:
  redis:
    container_name: branvia_redis_prod
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    container_name: branvia_postgres_prod
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MAX_CONNECTIONS: 200  # Increased connection limit
      POSTGRES_SHARED_BUFFERS: 256MB  # Better memory management
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB  # Optimize cache
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # BullMQ Worker service
  worker:
    container_name: branvia_worker_prod
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - POSTGRES_URL=${POSTGRES_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    deploy:
      replicas: 4  # Increased from 2 to 4 for better capacity
      resources:
        limits:
          memory: 2G  # Increased from 1G to 2G
        reservations:
          memory: 1G  # Increased from 512M to 1G

volumes:
  redis_data:
  postgres_data: 