FROM branvia-base AS base

# build stage
FROM base AS builder
WORKDIR /app/worker

COPY worker/ ./

RUN pnpm install
RUN pnpm run build

CMD cd ../packages/database && pnpm run migrate:prod && cd ../../worker && pnpm start