FROM branvia-base AS base

# build stage
FROM base AS builder
WORKDIR /app/web

COPY web/ ./
COPY .env ./

RUN pnpm install
RUN pnpm dotenv -e .env pnpm run build

CMD cd ../packages/database && pnpm run migrate:prod && cd ../../web && pnpm start