import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/_components/ui/Navbar";
import { UserProvider } from "@/_lib/_providers";
import { auth } from "@/_lib/_auth/auth";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers()
  })
  const user = session?.user
  return (
    <html lang="en">
      <body>
        <UserProvider initialUser={user}>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
